require("dotenv").config()
const express = require("express")
const cookieParser = require("cookie-parser")
const authRoutes = require("./routes/authRoutes")
const blogRoutes = require("./routes/blogRoutes")
const PORT = process.env.PORT
const app = express()
app.use(cookieParser())
app.use(express.json())
app.use("/api/auth/", authRoutes)
app.use("/api/v1/", blogRoutes)
app.listen(PORT, () => console.log(`server running on PORT:${PORT}.`))
